import * as React from "react";
import dynamic from "next/dynamic";
import {
  Avatar,
  Box,
  Card,
  CardContent,
  Stack,
  SvgIcon,
  Typography,
  Unstable_Grid2 as Grid,
  Button,
} from "@mui/material";

import { stringToColor } from "@/utils";
import { ChartLine } from "@/components/Chart/LineChart";
import ChartCardTemplate from "@/components/Card/ChartCard";

const DynamicLineChart = dynamic(() => import("@/components/Chart/LineChart"), {
  loading: () => <>Loading...</>,
  ssr: false,
});

const XAXIS_KEY_NAME = "release_year";
const YAXIS_KEY_NAME = "num";

const MOCK_GAME_RELEASED = [
  { release_year: 2022, num: 13960 },
  { release_year: 2018, num: 7853 },
  { release_year: 2015, num: 2620 },
  { release_year: 2007, num: 102 },
  { release_year: 2002, num: 1 },
  { release_year: 2013, num: 482 },
  { release_year: 2012, num: 350 },
  { release_year: 1999, num: 3 },
  { release_year: 2008, num: 166 },
  { release_year: 2019, num: 7614 },
  { release_year: 1998, num: 1 },
  { release_year: 2006, num: 69 },
  { release_year: 2021, num: 12306 },
  { release_year: 1997, num: 2 },
  { release_year: 2001, num: 4 },
  { release_year: 2011, num: 281 },
  { release_year: 2017, num: 6182 },
  { release_year: 2003, num: 3 },
  { release_year: 2014, num: 1590 },
  { release_year: 2020, num: 9473 },
  { release_year: 2010, num: 297 },
  { release_year: 2000, num: 2 },
  { release_year: 2005, num: 7 },
  { release_year: 2004, num: 7 },
  { release_year: 2016, num: 4311 },
  { release_year: 2009, num: 328 },
];
const MOCK_GOOD_GAME_RELEASED = [
  { release_year: 2007, num: 21 },
  { release_year: 2018, num: 18 },
  { release_year: 2015, num: 20 },
  { release_year: 2022, num: 14 },
  { release_year: 2017, num: 23 },
  { release_year: 2014, num: 11 },
  { release_year: 2020, num: 22 },
  { release_year: 2010, num: 20 },
  { release_year: 2004, num: 3 },
  { release_year: 2000, num: 1 },
  { release_year: 2005, num: 1 },
  { release_year: 2019, num: 15 },
  { release_year: 2006, num: 9 },
  { release_year: 2008, num: 14 },
  { release_year: 2021, num: 17 },
  { release_year: 2011, num: 19 },
  { release_year: 1998, num: 1 },
  { release_year: 2016, num: 20 },
  { release_year: 2009, num: 22 },
  { release_year: 2013, num: 18 },
  { release_year: 2012, num: 15 },
  { release_year: 2002, num: 1 },
];
const MOCK_TOP_10_LANG_RELEASED = [
  { language_name: "Russian", release_year: 2002, num: 1 },
  { language_name: "Italian", release_year: 2002, num: 1 },
  { language_name: "Russian", release_year: 2011, num: 68 },
  { language_name: "Russian", release_year: 2021, num: 2615 },
  { language_name: "German", release_year: 2004, num: 5 },
  { language_name: "Spanish - Spain", release_year: 2011, num: 139 },
  { language_name: "English", release_year: 2016, num: 4289 },
  { language_name: "Simplified Chinese", release_year: 2015, num: 280 },
  { language_name: "Italian", release_year: 2022, num: 1574 },
  { language_name: "Korean", release_year: 2012, num: 24 },
  { language_name: "Russian", release_year: 2022, num: 2279 },
  { language_name: "Simplified Chinese", release_year: 2017, num: 1173 },
  { language_name: "English", release_year: 2020, num: 8984 },
  { language_name: "Spanish - Spain", release_year: 2016, num: 971 },
  { language_name: "Simplified Chinese", release_year: 2009, num: 4 },
  { language_name: "Russian", release_year: 2000, num: 1 },
  { language_name: "English", release_year: 2019, num: 7234 },
  { language_name: "Spanish - Spain", release_year: 2003, num: 2 },
  { language_name: "English", release_year: 1999, num: 3 },
  { language_name: "Russian", release_year: 1999, num: 1 },
  { language_name: "French", release_year: 2016, num: 1037 },
  { language_name: "Spanish - Spain", release_year: 2005, num: 4 },
  { language_name: "English", release_year: 2022, num: 12006 },
  { language_name: "Japanese", release_year: 2008, num: 6 },
  { language_name: "Spanish - Spain", release_year: 2007, num: 46 },
  { language_name: "Italian", release_year: 2013, num: 227 },
  { language_name: "Spanish - Spain", release_year: 2013, num: 236 },
  { language_name: "Russian", release_year: 2008, num: 20 },
  { language_name: "Portuguese - Brazil", release_year: 2022, num: 1432 },
  { language_name: "Spanish - Spain", release_year: 2014, num: 535 },
  { language_name: "Portuguese - Brazil", release_year: 2017, num: 643 },
  { language_name: "Japanese", release_year: 2013, num: 86 },
  { language_name: "Italian", release_year: 2004, num: 5 },
  { language_name: "Italian", release_year: 2012, num: 142 },
  { language_name: "German", release_year: 2019, num: 1695 },
  { language_name: "Italian", release_year: 1998, num: 1 },
  { language_name: "English", release_year: 2015, num: 2603 },
  { language_name: "German", release_year: 2009, num: 136 },
  { language_name: "Korean", release_year: 2022, num: 1644 },
  { language_name: "Korean", release_year: 2013, num: 52 },
  { language_name: "Italian", release_year: 2019, num: 1067 },
  { language_name: "Italian", release_year: 2006, num: 24 },
  { language_name: "English", release_year: 2013, num: 482 },
  { language_name: "German", release_year: 2020, num: 2056 },
  { language_name: "Spanish - Spain", release_year: 1999, num: 1 },
  { language_name: "Italian", release_year: 2010, num: 102 },
  { language_name: "German", release_year: 2010, num: 137 },
  { language_name: "Korean", release_year: 1998, num: 1 },
  { language_name: "Simplified Chinese", release_year: 2014, num: 151 },
  { language_name: "Simplified Chinese", release_year: 2010, num: 6 },
  { language_name: "English", release_year: 2000, num: 2 },
  { language_name: "Japanese", release_year: 2021, num: 2311 },
  { language_name: "English", release_year: 2018, num: 7638 },
  { language_name: "Korean", release_year: 2010, num: 10 },
  { language_name: "German", release_year: 2021, num: 2454 },
  { language_name: "Russian", release_year: 2010, num: 44 },
  { language_name: "Simplified Chinese", release_year: 2016, num: 630 },
  { language_name: "Russian", release_year: 2007, num: 10 },
  { language_name: "Japanese", release_year: 2006, num: 6 },
  { language_name: "Japanese", release_year: 2010, num: 24 },
  { language_name: "Korean", release_year: 2005, num: 1 },
  { language_name: "Portuguese - Brazil", release_year: 2013, num: 91 },
  { language_name: "Russian", release_year: 2006, num: 14 },
  { language_name: "Italian", release_year: 2003, num: 2 },
  { language_name: "Simplified Chinese", release_year: 2007, num: 4 },
  { language_name: "Simplified Chinese", release_year: 2000, num: 2 },
  { language_name: "Simplified Chinese", release_year: 2022, num: 3283 },
  { language_name: "Spanish - Spain", release_year: 2017, num: 1232 },
  { language_name: "Russian", release_year: 2013, num: 182 },
  { language_name: "Japanese", release_year: 2020, num: 1892 },
  { language_name: "Simplified Chinese", release_year: 2008, num: 5 },
  { language_name: "Japanese", release_year: 2011, num: 32 },
  { language_name: "Korean", release_year: 2004, num: 5 },
  { language_name: "Italian", release_year: 2021, num: 1593 },
  { language_name: "German", release_year: 2022, num: 2353 },
  { language_name: "Italian", release_year: 2015, num: 579 },
  { language_name: "Russian", release_year: 2018, num: 1718 },
  { language_name: "Portuguese - Brazil", release_year: 2012, num: 24 },
  { language_name: "English", release_year: 2001, num: 4 },
  { language_name: "Simplified Chinese", release_year: 2020, num: 2446 },
  { language_name: "French", release_year: 2004, num: 5 },
  { language_name: "Spanish - Spain", release_year: 2020, num: 1822 },
  { language_name: "French", release_year: 2001, num: 2 },
  { language_name: "Italian", release_year: 2009, num: 114 },
  { language_name: "Portuguese - Brazil", release_year: 2015, num: 332 },
  { language_name: "Japanese", release_year: 2007, num: 6 },
  { language_name: "English", release_year: 2012, num: 347 },
  { language_name: "Italian", release_year: 2011, num: 124 },
  { language_name: "Italian", release_year: 2001, num: 1 },
  { language_name: "Italian", release_year: 2016, num: 731 },
  { language_name: "Spanish - Spain", release_year: 2009, num: 116 },
  { language_name: "Portuguese - Brazil", release_year: 2009, num: 5 },
  { language_name: "Simplified Chinese", release_year: 2001, num: 1 },
  { language_name: "Portuguese - Brazil", release_year: 2020, num: 1110 },
  { language_name: "Spanish - Spain", release_year: 2019, num: 1456 },
  { language_name: "Japanese", release_year: 2016, num: 626 },
  { language_name: "French", release_year: 2007, num: 49 },
  { language_name: "Russian", release_year: 2009, num: 56 },
  { language_name: "Russian", release_year: 2020, num: 2140 },
  { language_name: "Simplified Chinese", release_year: 2013, num: 61 },
  { language_name: "Korean", release_year: 2015, num: 214 },
  { language_name: "Italian", release_year: 2000, num: 2 },
  { language_name: "Spanish - Spain", release_year: 2018, num: 1476 },
  { language_name: "Korean", release_year: 2020, num: 1180 },
  { language_name: "French", release_year: 1999, num: 2 },
  { language_name: "Italian", release_year: 2008, num: 55 },
  { language_name: "French", release_year: 1998, num: 1 },
  { language_name: "Korean", release_year: 2009, num: 7 },
  { language_name: "Korean", release_year: 2016, num: 346 },
  { language_name: "Spanish - Spain", release_year: 2021, num: 2206 },
  { language_name: "Simplified Chinese", release_year: 1999, num: 1 },
  { language_name: "Portuguese - Brazil", release_year: 2010, num: 1 },
  { language_name: "Portuguese - Brazil", release_year: 2016, num: 495 },
  { language_name: "Russian", release_year: 2017, num: 1291 },
  { language_name: "Portuguese - Brazil", release_year: 2021, num: 1493 },
  { language_name: "German", release_year: 1999, num: 2 },
  { language_name: "Russian", release_year: 2004, num: 3 },
  { language_name: "German", release_year: 2011, num: 163 },
  { language_name: "English", release_year: 2017, num: 6072 },
  { language_name: "English", release_year: 1998, num: 1 },
  { language_name: "French", release_year: 2020, num: 1999 },
  { language_name: "French", release_year: 2019, num: 1613 },
  { language_name: "French", release_year: 2014, num: 591 },
  { language_name: "Italian", release_year: 2017, num: 915 },
  { language_name: "English", release_year: 2004, num: 7 },
  { language_name: "Korean", release_year: 2008, num: 4 },
  { language_name: "French", release_year: 2021, num: 2434 },
  { language_name: "Korean", release_year: 2001, num: 1 },
  { language_name: "Russian", release_year: 2005, num: 2 },
  { language_name: "German", release_year: 2006, num: 26 },
  { language_name: "Portuguese - Brazil", release_year: 2019, num: 853 },
  { language_name: "Italian", release_year: 2014, num: 462 },
  { language_name: "German", release_year: 2014, num: 639 },
  { language_name: "Japanese", release_year: 2017, num: 941 },
  { language_name: "French", release_year: 2013, num: 264 },
  { language_name: "French", release_year: 2008, num: 70 },
  { language_name: "Korean", release_year: 2007, num: 7 },
  { language_name: "Simplified Chinese", release_year: 2019, num: 1952 },
  { language_name: "Portuguese - Brazil", release_year: 2011, num: 7 },
  { language_name: "Korean", release_year: 2011, num: 19 },
  { language_name: "Simplified Chinese", release_year: 2005, num: 1 },
  { language_name: "French", release_year: 2022, num: 2341 },
  { language_name: "Portuguese - Brazil", release_year: 2014, num: 193 },
  { language_name: "Simplified Chinese", release_year: 2018, num: 1743 },
  { language_name: "English", release_year: 2008, num: 164 },
  { language_name: "English", release_year: 2002, num: 1 },
  { language_name: "Spanish - Spain", release_year: 2000, num: 2 },
  { language_name: "French", release_year: 2002, num: 1 },
  { language_name: "Korean", release_year: 2014, num: 126 },
  { language_name: "Simplified Chinese", release_year: 2012, num: 22 },
  { language_name: "Russian", release_year: 2014, num: 416 },
  { language_name: "German", release_year: 1998, num: 1 },
  { language_name: "Japanese", release_year: 2012, num: 57 },
  { language_name: "Simplified Chinese", release_year: 2006, num: 4 },
  { language_name: "Italian", release_year: 1999, num: 1 },
  { language_name: "Korean", release_year: 2019, num: 931 },
  { language_name: "Korean", release_year: 2017, num: 593 },
  { language_name: "Spanish - Spain", release_year: 2015, num: 729 },
  { language_name: "Spanish - Spain", release_year: 1998, num: 1 },
  { language_name: "Spanish - Spain", release_year: 2001, num: 2 },
  { language_name: "French", release_year: 2011, num: 151 },
  { language_name: "Portuguese - Brazil", release_year: 2008, num: 2 },
  { language_name: "Russian", release_year: 2012, num: 93 },
  { language_name: "French", release_year: 2005, num: 4 },
  { language_name: "German", release_year: 2002, num: 1 },
  { language_name: "German", release_year: 2017, num: 1375 },
  { language_name: "Russian", release_year: 2016, num: 943 },
  { language_name: "German", release_year: 2012, num: 182 },
  { language_name: "French", release_year: 2012, num: 166 },
  { language_name: "Portuguese - Brazil", release_year: 2006, num: 1 },
  { language_name: "French", release_year: 2006, num: 28 },
  { language_name: "Japanese", release_year: 2022, num: 2457 },
  { language_name: "Simplified Chinese", release_year: 2021, num: 2993 },
  { language_name: "English", release_year: 2010, num: 297 },
  { language_name: "Japanese", release_year: 2005, num: 1 },
  { language_name: "Italian", release_year: 2020, num: 1384 },
  { language_name: "German", release_year: 2001, num: 3 },
  { language_name: "Japanese", release_year: 2009, num: 19 },
  { language_name: "Japanese", release_year: 2019, num: 1435 },
  { language_name: "Spanish - Spain", release_year: 2010, num: 110 },
  { language_name: "Simplified Chinese", release_year: 2004, num: 5 },
  { language_name: "Simplified Chinese", release_year: 1998, num: 1 },
  { language_name: "Portuguese - Brazil", release_year: 2007, num: 1 },
  { language_name: "German", release_year: 2000, num: 2 },
  { language_name: "English", release_year: 2005, num: 7 },
  { language_name: "German", release_year: 2005, num: 4 },
  { language_name: "German", release_year: 2018, num: 1628 },
  { language_name: "Italian", release_year: 2005, num: 4 },
  { language_name: "English", release_year: 2021, num: 10935 },
  { language_name: "English", release_year: 2014, num: 1584 },
  { language_name: "English", release_year: 2006, num: 69 },
  { language_name: "German", release_year: 2013, num: 288 },
  { language_name: "German", release_year: 2003, num: 2 },
  { language_name: "Portuguese - Brazil", release_year: 2018, num: 839 },
  { language_name: "Spanish - Spain", release_year: 2004, num: 5 },
  { language_name: "Spanish - Spain", release_year: 2012, num: 153 },
  { language_name: "Korean", release_year: 1999, num: 2 },
  { language_name: "Spanish - Spain", release_year: 2002, num: 1 },
  { language_name: "English", release_year: 2003, num: 3 },
  { language_name: "English", release_year: 2007, num: 102 },
  { language_name: "Korean", release_year: 2006, num: 4 },
  { language_name: "English", release_year: 1997, num: 2 },
  { language_name: "Simplified Chinese", release_year: 2011, num: 12 },
  { language_name: "German", release_year: 2016, num: 1095 },
  { language_name: "Japanese", release_year: 2018, num: 1235 },
  { language_name: "French", release_year: 2010, num: 119 },
  { language_name: "Japanese", release_year: 2015, num: 416 },
  { language_name: "Korean", release_year: 2018, num: 827 },
  { language_name: "Japanese", release_year: 2004, num: 3 },
  { language_name: "Spanish - Spain", release_year: 2006, num: 23 },
  { language_name: "Italian", release_year: 2018, num: 1072 },
  { language_name: "Korean", release_year: 2021, num: 1498 },
  { language_name: "Russian", release_year: 2015, num: 619 },
  { language_name: "Italian", release_year: 2007, num: 40 },
  { language_name: "Japanese", release_year: 2014, num: 213 },
  { language_name: "Spanish - Spain", release_year: 2022, num: 2176 },
  { language_name: "French", release_year: 2003, num: 2 },
  { language_name: "Korean", release_year: 2000, num: 2 },
  { language_name: "English", release_year: 2011, num: 281 },
  { language_name: "Russian", release_year: 2001, num: 1 },
  { language_name: "German", release_year: 2007, num: 47 },
  { language_name: "French", release_year: 2017, num: 1320 },
  { language_name: "German", release_year: 2015, num: 834 },
  { language_name: "French", release_year: 2018, num: 1581 },
  { language_name: "French", release_year: 2015, num: 768 },
  { language_name: "Spanish - Spain", release_year: 2008, num: 60 },
  { language_name: "French", release_year: 2009, num: 141 },
  { language_name: "English", release_year: 2009, num: 320 },
  { language_name: "Russian", release_year: 2019, num: 1740 },
  { language_name: "German", release_year: 2008, num: 64 },
  { language_name: "French", release_year: 2000, num: 2 },
];
const MOCK_TOP_10_GENRE_RELEASED = [
  { genre_name: "Indie", release_year: 2022, num: 8711 },
  { genre_name: "Indie", release_year: 2021, num: 8130 },
  { genre_name: "Indie", release_year: 2020, num: 7029 },
  { genre_name: "Indie", release_year: 2018, num: 6013 },
  { genre_name: "Indie", release_year: 2019, num: 5768 },
  { genre_name: "Casual", release_year: 2022, num: 5682 },
  { genre_name: "Casual", release_year: 2021, num: 5144 },
  { genre_name: "Adventure", release_year: 2022, num: 5102 },
  { genre_name: "Action", release_year: 2022, num: 5100 },
  { genre_name: "Action", release_year: 2021, num: 4637 },
  { genre_name: "Adventure", release_year: 2021, num: 4633 },
  { genre_name: "Indie", release_year: 2017, num: 4385 },
  { genre_name: "Casual", release_year: 2020, num: 4136 },
  { genre_name: "Action", release_year: 2020, num: 3980 },
  { genre_name: "Adventure", release_year: 2020, num: 3665 },
  { genre_name: "Casual", release_year: 2018, num: 3508 },
  { genre_name: "Action", release_year: 2018, num: 3309 },
  { genre_name: "Casual", release_year: 2019, num: 3183 },
  { genre_name: "Action", release_year: 2019, num: 3155 },
  { genre_name: "Indie", release_year: 2016, num: 3031 },
  { genre_name: "Adventure", release_year: 2019, num: 2983 },
  { genre_name: "Adventure", release_year: 2018, num: 2867 },
  { genre_name: "Action", release_year: 2017, num: 2725 },
  { genre_name: "Simulation", release_year: 2022, num: 2558 },
  { genre_name: "Casual", release_year: 2017, num: 2462 },
  { genre_name: "RPG", release_year: 2022, num: 2456 },
  { genre_name: "Strategy", release_year: 2022, num: 2442 },
  { genre_name: "Adventure", release_year: 2017, num: 2342 },
  { genre_name: "Simulation", release_year: 2021, num: 2296 },
  { genre_name: "Early Access", release_year: 2022, num: 2232 },
  { genre_name: "Strategy", release_year: 2021, num: 2130 },
  { genre_name: "RPG", release_year: 2021, num: 2108 },
  { genre_name: "Simulation", release_year: 2020, num: 1985 },
  { genre_name: "Indie", release_year: 2015, num: 1891 },
  { genre_name: "Action", release_year: 2016, num: 1877 },
  { genre_name: "Strategy", release_year: 2020, num: 1814 },
  { genre_name: "RPG", release_year: 2020, num: 1642 },
  { genre_name: "Casual", release_year: 2016, num: 1602 },
  { genre_name: "Adventure", release_year: 2016, num: 1571 },
  { genre_name: "Simulation", release_year: 2018, num: 1544 },
  { genre_name: "Early Access", release_year: 2021, num: 1509 },
  { genre_name: "Simulation", release_year: 2019, num: 1500 },
  { genre_name: "Strategy", release_year: 2019, num: 1422 },
  { genre_name: "RPG", release_year: 2019, num: 1418 },
  { genre_name: "Strategy", release_year: 2018, num: 1389 },
  { genre_name: "Free to Play", release_year: 2022, num: 1266 },
  { genre_name: "RPG", release_year: 2018, num: 1215 },
  { genre_name: "Simulation", release_year: 2017, num: 1165 },
  { genre_name: "Action", release_year: 2015, num: 1136 },
  { genre_name: "Strategy", release_year: 2017, num: 1121 },
  { genre_name: "Early Access", release_year: 2020, num: 1074 },
  { genre_name: "Adventure", release_year: 2015, num: 1013 },
  { genre_name: "Free to Play", release_year: 2021, num: 998 },
  { genre_name: "Indie", release_year: 2014, num: 896 },
  { genre_name: "Free to Play", release_year: 2020, num: 893 },
  { genre_name: "RPG", release_year: 2017, num: 871 },
  { genre_name: "Early Access", release_year: 2019, num: 860 },
  { genre_name: "Simulation", release_year: 2016, num: 833 },
  { genre_name: "Strategy", release_year: 2016, num: 800 },
  { genre_name: "Early Access", release_year: 2018, num: 799 },
  { genre_name: "Casual", release_year: 2015, num: 773 },
  { genre_name: "Action", release_year: 2014, num: 653 },
  { genre_name: "Early Access", release_year: 2017, num: 609 },
  { genre_name: "Free to Play", release_year: 2019, num: 607 },
  { genre_name: "RPG", release_year: 2016, num: 606 },
  { genre_name: "Strategy", release_year: 2015, num: 589 },
  { genre_name: "Adventure", release_year: 2014, num: 586 },
  { genre_name: "Free to Play", release_year: 2018, num: 575 },
  { genre_name: "Sports", release_year: 2022, num: 555 },
  { genre_name: "Racing", release_year: 2022, num: 504 },
  { genre_name: "RPG", release_year: 2015, num: 498 },
  { genre_name: "Sports", release_year: 2020, num: 471 },
  { genre_name: "Simulation", release_year: 2015, num: 458 },
  { genre_name: "Sports", release_year: 2021, num: 458 },
  { genre_name: "Casual", release_year: 2014, num: 418 },
  { genre_name: "Racing", release_year: 2021, num: 416 },
  { genre_name: "Sports", release_year: 2018, num: 415 },
  { genre_name: "Free to Play", release_year: 2017, num: 406 },
  { genre_name: "Early Access", release_year: 2016, num: 405 },
  { genre_name: "Sports", release_year: 2019, num: 369 },
  { genre_name: "Massively Multiplayer", release_year: 2022, num: 351 },
  { genre_name: "Strategy", release_year: 2014, num: 348 },
  { genre_name: "Sports", release_year: 2017, num: 341 },
  { genre_name: "Racing", release_year: 2020, num: 331 },
  { genre_name: "Racing", release_year: 2018, num: 294 },
  { genre_name: "Massively Multiplayer", release_year: 2021, num: 290 },
  { genre_name: "RPG", release_year: 2014, num: 284 },
  { genre_name: "Free to Play", release_year: 2016, num: 282 },
  { genre_name: "Racing", release_year: 2019, num: 281 },
  { genre_name: "Indie", release_year: 2013, num: 270 },
  { genre_name: "Violent", release_year: 2017, num: 262 },
  { genre_name: "Massively Multiplayer", release_year: 2020, num: 254 },
  { genre_name: "Simulation", release_year: 2014, num: 241 },
  { genre_name: "Action", release_year: 2013, num: 240 },
  { genre_name: "Sports", release_year: 2016, num: 236 },
  { genre_name: "Racing", release_year: 2017, num: 221 },
  { genre_name: "Massively Multiplayer", release_year: 2019, num: 209 },
  { genre_name: "Massively Multiplayer", release_year: 2018, num: 206 },
  { genre_name: "Violent", release_year: 2018, num: 185 },
  { genre_name: "Action", release_year: 2012, num: 180 },
  { genre_name: "Adventure", release_year: 2013, num: 173 },
  { genre_name: "Indie", release_year: 2012, num: 173 },
  { genre_name: "Massively Multiplayer", release_year: 2017, num: 171 },
  { genre_name: "Early Access", release_year: 2015, num: 163 },
  { genre_name: "Gore", release_year: 2017, num: 160 },
  { genre_name: "Free to Play", release_year: 2015, num: 150 },
  { genre_name: "Racing", release_year: 2016, num: 148 },
  { genre_name: "Action", release_year: 2011, num: 123 },
  { genre_name: "Utilities", release_year: 2019, num: 119 },
  { genre_name: "Action", release_year: 2010, num: 115 },
  { genre_name: "Action", release_year: 2009, num: 111 },
  { genre_name: "Massively Multiplayer", release_year: 2016, num: 111 },
  { genre_name: "Utilities", release_year: 2021, num: 111 },
  { genre_name: "Adventure", release_year: 2012, num: 107 },
  { genre_name: "Strategy", release_year: 2013, num: 105 },
  { genre_name: "Gore", release_year: 2018, num: 105 },
  { genre_name: "Indie", release_year: 2011, num: 105 },
  { genre_name: "Sports", release_year: 2015, num: 100 },
  { genre_name: "Utilities", release_year: 2022, num: 99 },
  { genre_name: "Racing", release_year: 2015, num: 97 },
  { genre_name: "Utilities", release_year: 2020, num: 96 },
  { genre_name: "Utilities", release_year: 2018, num: 94 },
  { genre_name: "RPG", release_year: 2013, num: 91 },
  { genre_name: "Casual", release_year: 2013, num: 88 },
  { genre_name: "Utilities", release_year: 2017, num: 88 },
  { genre_name: "Strategy", release_year: 2011, num: 85 },
  { genre_name: "Strategy", release_year: 2012, num: 83 },
  { genre_name: "Simulation", release_year: 2013, num: 78 },
  { genre_name: "Adventure", release_year: 2009, num: 77 },
  { genre_name: "Casual", release_year: 2010, num: 77 },
  { genre_name: "Design & Illustration", release_year: 2017, num: 74 },
  { genre_name: "Indie", release_year: 2010, num: 70 },
  { genre_name: "Strategy", release_year: 2009, num: 69 },
  { genre_name: "Strategy", release_year: 2010, num: 67 },
  { genre_name: "Action", release_year: 2008, num: 64 },
  { genre_name: "Indie", release_year: 2009, num: 64 },
  { genre_name: "RPG", release_year: 2012, num: 63 },
  { genre_name: "Adventure", release_year: 2011, num: 63 },
  { genre_name: "Racing", release_year: 2014, num: 62 },
  { genre_name: "Casual", release_year: 2009, num: 62 },
  { genre_name: "Utilities", release_year: 2016, num: 62 },
  { genre_name: "Free to Play", release_year: 2014, num: 61 },
  { genre_name: "Nudity", release_year: 2017, num: 60 },
  { genre_name: "Action", release_year: 2007, num: 59 },
  { genre_name: "Design & Illustration", release_year: 2020, num: 59 },
  { genre_name: "Education", release_year: 2017, num: 59 },
  { genre_name: "Massively Multiplayer", release_year: 2015, num: 58 },
  { genre_name: "Adventure", release_year: 2010, num: 57 },
  { genre_name: "Early Access", release_year: 2014, num: 56 },
  { genre_name: "Design & Illustration", release_year: 2021, num: 56 },
  { genre_name: "Casual", release_year: 2012, num: 55 },
  { genre_name: "Design & Illustration", release_year: 2019, num: 55 },
  { genre_name: "Violent", release_year: 2016, num: 53 },
  { genre_name: "Design & Illustration", release_year: 2018, num: 52 },
  { genre_name: "Simulation", release_year: 2009, num: 52 },
  { genre_name: "Animation & Modeling", release_year: 2017, num: 52 },
  { genre_name: "Sports", release_year: 2014, num: 51 },
  { genre_name: "Education", release_year: 2020, num: 50 },
  { genre_name: "Sexual Content", release_year: 2017, num: 50 },
  { genre_name: "Animation & Modeling", release_year: 2020, num: 49 },
  { genre_name: "Education", release_year: 2022, num: 49 },
  { genre_name: "Animation & Modeling", release_year: 2022, num: 48 },
  { genre_name: "Education", release_year: 2019, num: 48 },
  { genre_name: "Education", release_year: 2021, num: 47 },
  { genre_name: "Video Production", release_year: 2017, num: 47 },
  { genre_name: "Animation & Modeling", release_year: 2018, num: 47 },
  { genre_name: "RPG", release_year: 2011, num: 46 },
  { genre_name: "Animation & Modeling", release_year: 2021, num: 46 },
  { genre_name: "Design & Illustration", release_year: 2022, num: 46 },
  { genre_name: "Education", release_year: 2018, num: 46 },
  { genre_name: "RPG", release_year: 2009, num: 45 },
  { genre_name: "Casual", release_year: 2011, num: 45 },
  { genre_name: "Game Development", release_year: 2021, num: 45 },
  { genre_name: "Sexual Content", release_year: 2018, num: 44 },
  { genre_name: "Design & Illustration", release_year: 2016, num: 43 },
  { genre_name: "Casual", release_year: 2008, num: 42 },
  { genre_name: "RPG", release_year: 2010, num: 40 },
  { genre_name: "Nudity", release_year: 2018, num: 40 },
  { genre_name: "Game Development", release_year: 2022, num: 40 },
  { genre_name: "Animation & Modeling", release_year: 2019, num: 39 },
  { genre_name: "Simulation", release_year: 2012, num: 39 },
  { genre_name: "Video Production", release_year: 2021, num: 39 },
  { genre_name: "Strategy", release_year: 2008, num: 37 },
  { genre_name: "Video Production", release_year: 2018, num: 36 },
  { genre_name: "Video Production", release_year: 2022, num: 35 },
  { genre_name: "Gore", release_year: 2016, num: 33 },
  { genre_name: "Video Production", release_year: 2020, num: 33 },
  { genre_name: "Education", release_year: 2016, num: 32 },
  { genre_name: "Simulation", release_year: 2010, num: 32 },
  { genre_name: "Game Development", release_year: 2019, num: 32 },
  { genre_name: "Animation & Modeling", release_year: 2016, num: 30 },
  { genre_name: "Game Development", release_year: 2020, num: 29 },
  { genre_name: "Utilities", release_year: 2015, num: 29 },
  { genre_name: "Simulation", release_year: 2011, num: 29 },
  { genre_name: "Strategy", release_year: 2006, num: 28 },
  { genre_name: "Audio Production", release_year: 2017, num: 28 },
  { genre_name: "Massively Multiplayer", release_year: 2014, num: 27 },
  { genre_name: "Audio Production", release_year: 2020, num: 27 },
  { genre_name: "Adventure", release_year: 2008, num: 27 },
  { genre_name: "Software Training", release_year: 2015, num: 27 },
  { genre_name: "Indie", release_year: 2008, num: 26 },
  { genre_name: "Free to Play", release_year: 2013, num: 26 },
  { genre_name: "Strategy", release_year: 2007, num: 25 },
  { genre_name: "Software Training", release_year: 2019, num: 25 },
  { genre_name: "Audio Production", release_year: 2021, num: 25 },
  { genre_name: "Software Training", release_year: 2022, num: 24 },
  { genre_name: "Audio Production", release_year: 2018, num: 24 },
  { genre_name: "Video Production", release_year: 2019, num: 24 },
  { genre_name: "Simulation", release_year: 2008, num: 23 },
  { genre_name: "Utilities", release_year: 2014, num: 23 },
  { genre_name: "Audio Production", release_year: 2019, num: 22 },
  { genre_name: "Software Training", release_year: 2020, num: 22 },
  { genre_name: "Free to Play", release_year: 2012, num: 22 },
  { genre_name: "Design & Illustration", release_year: 2015, num: 21 },
  { genre_name: "Audio Production", release_year: 2016, num: 21 },
  { genre_name: "Software Training", release_year: 2021, num: 20 },
  { genre_name: "Photo Editing", release_year: 2021, num: 20 },
  { genre_name: "Software Training", release_year: 2018, num: 19 },
  { genre_name: "Action", release_year: 2006, num: 19 },
  { genre_name: "Audio Production", release_year: 2022, num: 19 },
  { genre_name: "Casual", release_year: 2006, num: 19 },
  { genre_name: "Racing", release_year: 2013, num: 18 },
  { genre_name: "Photo Editing", release_year: 2017, num: 18 },
  { genre_name: "Design & Illustration", release_year: 2014, num: 18 },
  { genre_name: "Software Training", release_year: 2017, num: 18 },
  { genre_name: "Video Production", release_year: 2016, num: 18 },
  { genre_name: "Massively Multiplayer", release_year: 2013, num: 16 },
  { genre_name: "Web Publishing", release_year: 2020, num: 16 },
  { genre_name: "Software Training", release_year: 2016, num: 16 },
  { genre_name: "RPG", release_year: 2008, num: 15 },
  { genre_name: "Animation & Modeling", release_year: 2015, num: 15 },
  { genre_name: "Nudity", release_year: 2016, num: 15 },
  { genre_name: "Massively Multiplayer", release_year: 2012, num: 15 },
  { genre_name: "Web Publishing", release_year: 2019, num: 15 },
  { genre_name: "Sports", release_year: 2013, num: 14 },
  { genre_name: "Free to Play", release_year: 2011, num: 14 },
  { genre_name: "Web Publishing", release_year: 2021, num: 14 },
  { genre_name: "Photo Editing", release_year: 2022, num: 14 },
  { genre_name: "Game Development", release_year: 2018, num: 14 },
  { genre_name: "Photo Editing", release_year: 2018, num: 13 },
  { genre_name: "Education", release_year: 2015, num: 13 },
  { genre_name: "Web Publishing", release_year: 2017, num: 12 },
  { genre_name: "Casual", release_year: 2007, num: 12 },
  { genre_name: "Sexual Content", release_year: 2016, num: 12 },
  { genre_name: "Photo Editing", release_year: 2019, num: 12 },
  { genre_name: "Photo Editing", release_year: 2020, num: 12 },
  { genre_name: "Web Publishing", release_year: 2022, num: 11 },
  { genre_name: "Indie", release_year: 2006, num: 11 },
  { genre_name: "Racing", release_year: 2011, num: 11 },
  { genre_name: "Racing", release_year: 2012, num: 11 },
  { genre_name: "Racing", release_year: 2009, num: 10 },
  { genre_name: "RPG", release_year: 2007, num: 10 },
  { genre_name: "Massively Multiplayer", release_year: 2011, num: 10 },
  { genre_name: "Photo Editing", release_year: 2016, num: 10 },
  { genre_name: "Web Publishing", release_year: 2018, num: 10 },
  { genre_name: "Racing", release_year: 2008, num: 10 },
  { genre_name: "Animation & Modeling", release_year: 2014, num: 10 },
  { genre_name: "Adventure", release_year: 2007, num: 9 },
  { genre_name: "Video Production", release_year: 2015, num: 9 },
  { genre_name: "Education", release_year: 2014, num: 9 },
  { genre_name: "Indie", release_year: 2007, num: 8 },
  { genre_name: "Photo Editing", release_year: 2015, num: 8 },
  { genre_name: "Web Publishing", release_year: 2015, num: 8 },
  { genre_name: "Software Training", release_year: 2014, num: 8 },
  { genre_name: "Racing", release_year: 2010, num: 8 },
  { genre_name: "Sports", release_year: 2009, num: 8 },
  { genre_name: "Audio Production", release_year: 2015, num: 7 },
  { genre_name: "Game Development", release_year: 2016, num: 7 },
  { genre_name: "Sports", release_year: 2011, num: 7 },
  { genre_name: "Utilities", release_year: 2013, num: 7 },
  { genre_name: "Action", release_year: 2004, num: 7 },
  { genre_name: "Sports", release_year: 2012, num: 6 },
  { genre_name: "Web Publishing", release_year: 2016, num: 6 },
  { genre_name: "Video Production", release_year: 2014, num: 6 },
  { genre_name: "Audio Production", release_year: 2014, num: 6 },
  { genre_name: "Accounting", release_year: 2017, num: 6 },
  { genre_name: "Game Development", release_year: 2015, num: 6 },
  { genre_name: "RPG", release_year: 2006, num: 5 },
  { genre_name: "Early Access", release_year: 2013, num: 5 },
  { genre_name: "Accounting", release_year: 2018, num: 5 },
  { genre_name: "Accounting", release_year: 2016, num: 4 },
  { genre_name: "Racing", release_year: 2007, num: 4 },
  { genre_name: "Racing", release_year: 2006, num: 4 },
  { genre_name: "Violent", release_year: 2015, num: 4 },
  { genre_name: "Software Training", release_year: 2013, num: 4 },
  { genre_name: "Massively Multiplayer", release_year: 2009, num: 4 },
  { genre_name: "Animation & Modeling", release_year: 2013, num: 4 },
  { genre_name: "RPG", release_year: 2005, num: 4 },
  { genre_name: "Sports", release_year: 2008, num: 3 },
  { genre_name: "Gore", release_year: 2015, num: 3 },
  { genre_name: "Audio Production", release_year: 2013, num: 3 },
  { genre_name: "Indie", release_year: 2005, num: 3 },
  { genre_name: "Game Development", release_year: 2017, num: 3 },
  { genre_name: "Accounting", release_year: 2020, num: 3 },
  { genre_name: "Web Publishing", release_year: 2014, num: 3 },
  { genre_name: "Photo Editing", release_year: 2014, num: 3 },
  { genre_name: "Action", release_year: 2001, num: 3 },
  { genre_name: "Education", release_year: 2013, num: 3 },
  { genre_name: "Web Publishing", release_year: 2013, num: 3 },
  { genre_name: "Action", release_year: 1999, num: 3 },
  { genre_name: "Sports", release_year: 2010, num: 3 },
  { genre_name: "Action", release_year: 2005, num: 2 },
  { genre_name: "RPG", release_year: 2001, num: 2 },
  { genre_name: "Action", release_year: 2003, num: 2 },
  { genre_name: "Design & Illustration", release_year: 2013, num: 2 },
  { genre_name: "Free to Play", release_year: 2010, num: 2 },
  { genre_name: "Massively Multiplayer", release_year: 2010, num: 2 },
  { genre_name: "Action", release_year: 2000, num: 2 },
  { genre_name: "Strategy", release_year: 2005, num: 2 },
  { genre_name: "Animation & Modeling", release_year: 2012, num: 2 },
  { genre_name: "Indie", release_year: 1997, num: 2 },
  { genre_name: "Free to Play", release_year: 2008, num: 2 },
  { genre_name: "Indie", release_year: 2003, num: 2 },
  { genre_name: "Gore", release_year: 2013, num: 2 },
  { genre_name: "Game Development", release_year: 2013, num: 2 },
  { genre_name: "Accounting", release_year: 2019, num: 2 },
  { genre_name: "Action", release_year: 1997, num: 2 },
  { genre_name: "Video Production", release_year: 2013, num: 2 },
  { genre_name: "Free to Play", release_year: 2009, num: 2 },
  { genre_name: "Violent", release_year: 2014, num: 1 },
  { genre_name: "Violent", release_year: 2021, num: 1 },
  { genre_name: "Short", release_year: 2020, num: 1 },
  { genre_name: "Gore", release_year: 2012, num: 1 },
  { genre_name: "Racing", release_year: 1997, num: 1 },
  { genre_name: "Design & Illustration", release_year: 2012, num: 1 },
  { genre_name: "Casual", release_year: 2003, num: 1 },
  { genre_name: "Free to Play", release_year: 2007, num: 1 },
  { genre_name: "Accounting", release_year: 2021, num: 1 },
  { genre_name: "Adventure", release_year: 2002, num: 1 },
  { genre_name: "Video Production", release_year: 2012, num: 1 },
  { genre_name: "Adventure", release_year: 1999, num: 1 },
  { genre_name: "RPG", release_year: 2003, num: 1 },
  { genre_name: "Nudity", release_year: 2014, num: 1 },
  { genre_name: "Strategy", release_year: 2003, num: 1 },
  { genre_name: "Episodic", release_year: 2020, num: 1 },
  { genre_name: "Simulation", release_year: 2007, num: 1 },
  { genre_name: "Movie", release_year: 2017, num: 1 },
  { genre_name: "Utilities", release_year: 2012, num: 1 },
  { genre_name: "Action", release_year: 1998, num: 1 },
  { genre_name: "Gore", release_year: 2019, num: 1 },
  { genre_name: "Nudity", release_year: 2009, num: 1 },
  { genre_name: "Simulation", release_year: 2006, num: 1 },
  { genre_name: "Strategy", release_year: 2001, num: 1 },
  { genre_name: "Accounting", release_year: 2022, num: 1 },
  { genre_name: "Indie", release_year: 2001, num: 1 },
  { genre_name: "Violent", release_year: 2012, num: 1 },
  { genre_name: "Violent", release_year: 2019, num: 1 },
  { genre_name: "Web Publishing", release_year: 2012, num: 1 },
  { genre_name: "360 Video", release_year: 2020, num: 1 },
  { genre_name: "Photo Editing", release_year: 2012, num: 1 },
  { genre_name: "Tutorial", release_year: 2020, num: 1 },
  { genre_name: "Action", release_year: 2002, num: 1 },
  { genre_name: "Documentary", release_year: 2020, num: 1 },
  { genre_name: "Violent", release_year: 2009, num: 1 },
  { genre_name: "Movie", release_year: 2020, num: 1 },
];

const MOCK_DATA = [
  {
    title: "Game Released",
    data: MOCK_GAME_RELEASED,
    syncId: "time-series",
    sql: `SELECT 
  YEAR (games.release_date) AS release_year,
  count(*) AS num
FROM games
WHERE games.release_date < '2023-01-01'
GROUP BY YEAR (games.release_date)`,
  },
  {
    title: "Good Game Released",
    data: MOCK_GOOD_GAME_RELEASED,
    syncId: "time-series",
    sql: `SELECT 
    YEAR (games.release_date) AS release_year,
    count(*) AS num
FROM games
WHERE games.release_date < '2023-01-01'
AND games.metacritic_score > 85
GROUP BY YEAR (games.release_date)`,
  },
  {
    title: "Top 10 Lang",
    data: MOCK_TOP_10_LANG_RELEASED,
    syncId: "time-series",
    field: "language_name",
    sql: `WITH top10_languages AS (
      SELECT 
          language_id,
          COUNT(app_id) AS num
      FROM supported_language
      GROUP BY language_id
      ORDER BY num DESC
      LIMIT 10
  )
  SELECT 
      l.language_name AS language_name,
      YEAR(g.release_date) AS release_year,
      COUNT(*) AS num
  FROM supported_language AS sl
  LEFT JOIN games g ON g.app_id = sl.app_id
  LEFT JOIN language l ON l.language_id = sl.language_id
  INNER JOIN top10_languages top10 ON top10.language_id = sl.language_id
  WHERE g.release_date < '2023-01-01'
  GROUP BY l.language_name, YEAR(g.release_date)
  `,
  },
  {
    title: "Top 10 Genre",
    data: MOCK_TOP_10_GENRE_RELEASED,
    syncId: "time-series",
    field: "genre_name",
    sql: `SELECT 
    genre.genre_name AS genre_name,
    YEAR(g.release_date) AS release_year,
    COUNT(*) AS num
FROM game_genre AS gg
LEFT JOIN games g ON g.app_id = gg.app_id
LEFT JOIN genre ON genre.genre_id = gg.genre_id
WHERE g.release_date < '2023-01-01'
GROUP BY genre.genre_name, YEAR(g.release_date)
ORDER BY num DESC
`,
  },
];

export default function TimeSeriesCardGroup() {
  return (
    <>
      <Grid
        container
        spacing={2}
        sx={{
          overflow: "auto",
        }}
      >
        {MOCK_DATA.map((item) => (
          <Grid key={item.title} xs={12} md={6}>
            <TimeSeriesCardTemplate
              title={item.title}
              data={item.data.sort((a, b) =>
                a.release_year > b.release_year ? 1 : -1
              )}
              multiLineField={item.field}
              syncId={item.syncId}
              sql={item.sql}
            />
          </Grid>
        ))}
      </Grid>
    </>
  );
}

const TimeSeriesCardTemplate = (props: {
  title: string;
  data: { [x: string]: string | number }[];
  multiLineField?: string;
  syncId?: string;
  sql?: string;
}) => {
  const { title, data, multiLineField, syncId, sql } = props;

  const [dataDemo, linesMemo] = React.useMemo(() => {
    const lines: ChartLine[] = [];
    const newLineObj: { [x: string]: ChartLine } = {};
    const newDataObj: {
      [x: string]: { [x: string]: string | number };
    } = {};
    if (!multiLineField) {
      lines.push({
        dataKey: "num",
        stroke: stringToColor("num"),
      });
      return [data, lines];
    }
    data.forEach((item) => {
      if (!newDataObj[item[XAXIS_KEY_NAME]]) {
        newDataObj[item[XAXIS_KEY_NAME]] = {};
      }
      newDataObj[item[XAXIS_KEY_NAME]][item[multiLineField]] = item.num;
      if (!newLineObj[item[multiLineField]]) {
        newLineObj[item[multiLineField]] = {
          dataKey: item[multiLineField] as string,
          stroke: stringToColor(item[multiLineField] as string),
        };
      }
    });
    const newData = Object.keys(newDataObj).map((key) => ({
      [XAXIS_KEY_NAME]: key,
      ...newDataObj[key],
    }));
    Object.keys(newLineObj).forEach((key) => {
      lines.push(newLineObj[key]);
    });
    return [newData, lines];
  }, [data, multiLineField]);

  return (
    <ChartCardTemplate title={title} sql={sql}>
      <DynamicLineChart
        xDataKey={XAXIS_KEY_NAME}
        data={dataDemo}
        lines={linesMemo}
        syncId={syncId}
      />
    </ChartCardTemplate>
  );
};
