export function retriveGameListByName(name: string) {
  const MOCK_GAME_LIST = [
    { id: 10, name: "Counter-Strike" },
    { id: 20, name: "Team Fortress Classic" },
    { id: 30, name: "Day of Defeat" },
    { id: 40, name: "Deathmatch Classic" },
    { id: 50, name: "Half-Life: Opposing Force" },
    { id: 60, name: "Ricochet" },
    { id: 70, name: "Half-Life" },
    { id: 80, name: "Counter-Strike: Condition Zero" },
    { id: 100, name: "Counter-Strike: Condition Zero" },
    { id: 130, name: "Half-Life: Blue Shift" },
    { id: 220, name: "Half-Life 2" },
    { id: 240, name: "Counter-Strike: Source" },
    { id: 280, name: "Half-Life: Source" },
    { id: 300, name: "Day of Defeat: Source" },
    { id: 320, name: "Half-Life 2: Deathmatch" },
    { id: 340, name: "Half-Life 2: Lost Coast" },
    { id: 360, name: "Half-Life Deathmatch: Source" },
    { id: 380, name: "Half-Life 2: Episode One" },
    { id: 400, name: "Portal" },
    { id: 420, name: "Half-Life 2: Episode Two" },
    { id: 440, name: "Team Fortress 2" },
    { id: 500, name: "Left 4 Dead" },
    { id: 550, name: "Left 4 Dead 2" },
    { id: 570, name: "Dota 2" },
    { id: 620, name: "Portal 2" },
    { id: 630, name: "Alien Swarm" },
    { id: 659, name: "Portal 2" },
    { id: 730, name: "Counter-Strike: Global Offensive" },
    { id: 1002, name: "Rag Doll Kung Fu" },
    { id: 1200, name: "Red Orchestra: Ostfront 41-45" },
    { id: 1250, name: "Killing Floor" },
    { id: 1300, name: "SiN Episodes: Emergence" },
    { id: 1313, name: "SiN: Gold" },
    { id: 1500, name: "Darwinia" },
    { id: 1510, name: "Uplink" },
    { id: 1520, name: "DEFCON" },
  ];

  return MOCK_GAME_LIST;
}
