import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import * as React from "react";
import {
  Avatar,
  Badge,
  Box,
  Button,
  IconButton,
  Stack,
  SvgIcon,
  Tooltip,
  useMediaQuery,
  Container,
  Typography,
} from "@mui/material";

import Layout from "@/components/Layout";
import TimeSeriesCardGroup from "@/sections/home/TimeSeriesCardGroup";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Layout
        headerProps={{
          title: "Data Insight",
        }}
      >
        {/* <Typography variant="h1">Overview</Typography> */}
        <TimeSeriesCardGroup />
      </Layout>
    </>
  );
}
