import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import * as React from "react";
import {
  Avatar,
  Badge,
  Box,
  Button,
  IconButton,
  Stack,
  SvgIcon,
  Tooltip,
  useMediaQuery,
  Container,
  Typography,
  Unstable_Grid2 as Grid,
} from "@mui/material";

import Layout from "@/components/Layout";
import TimeSeriesCardGroup from "@/sections/home/TimeSeriesCardGroup";
import TopTenCardGroup from "@/sections/home/TopTenCardGroup";
import PieCardGroup from "@/sections/home/PieCardGroup";
import GamePanelGroup from "@/sections/home/GamePanelGroup";
import CardGroup from "@/sections/home/CardGroup";

import { apRoutes } from "@/services/dataService/routes";
import { DataServiceApiHandler } from "@/services/dataService";

export default function Home(props: { ap: { id: string; data: any }[] }) {
  const { ap } = props;

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Layout
        headerProps={{
          title: "Data Insight",
        }}
      >
        <Grid
          container
          spacing={2}
          sx={{
            overflow: "auto",
          }}
        >
          <CardGroup data={ap} />
          <GamePanelGroup />

          {/* <TimeSeriesCardGroup />
          <TopTenCardGroup />
          <PieCardGroup /> */}
        </Grid>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const apResults = [];
  for (const route of apRoutes) {
    const dataServiceApi = new DataServiceApiHandler(`ap`, route.path);
    const { data } = await dataServiceApi.fetchData(
      `/ap`,
      route.path,
      undefined,
      true
    );
    apResults.push({ id: route.id, data });
  }
  return {
    props: {
      ap: apResults,
    }, // will be passed to the page component as props
  };
}
